[package]
name = "vcfbub"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rust-htslib = { version = "0.49.0", default-features = false }
clap = "4.5.23"
